apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: db03ib224-java-springboot
  janus-idp.io/tekton: db03ib224-java-springboot
  backstage.io/kubernetes-id: db03ib224-java-springboot
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: db03ib224-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
